-- El producto del que se acaba de hablar.
--
-- Un cliente pregunta "tienen botín urbano?", lee el precio y contesta
-- "talla 41". Ese segundo mensaje no nombra ningún producto: sin recordar
-- cuál era, el asistente lo leía como un mensaje suelto y le contestaba
-- "¿de qué distrito recogemos el envío?", que no tiene nada que ver.
--
-- Se guarda en la ficha y no en memoria del proceso a propósito: la
-- conversación sobrevive a un reinicio, y la pregunta de seguimiento puede
-- llegar veinte minutos después.
alter table leads add column if not exists ultimo_producto text;
