-- Parar el bot en UN chat concreto, sin parar el sistema.
--
-- El operador ve una conversación que se está torciendo -un reclamo, un
-- cliente que ya habló por teléfono, alguien a quien no conviene contestar
-- con un menú- y quiere atenderla él. Hasta ahora la única forma era cerrar
-- la ficha (`estado = calificado`), que apaga el bot de rebote pero además
-- da la preventa por terminada: la ficha se va a la bandeja como si se
-- hubiera cerrado bien.
--
-- Con esto es una decisión aparte y reversible: se pausa, se atiende a mano,
-- y se vuelve a soltar cuando convenga. Sin fecha de caducidad a propósito;
-- lo contrario sería que el bot volviera a hablar solo un martes cualquiera.
alter table contacts add column if not exists bot_pausado_at timestamptz;
