import { appShell } from './shell.js';

export function cuentasPage(opts: { nombreNegocio: string }): string {
  return appShell({ titulo: 'Cuentas', subtitulo: 'Cuentas independientes de la plataforma', nombreNegocio: opts.nombreNegocio,
    css: '.wrap{max-width:1200px;margin:auto}.card{background:var(--superficie);padding:22px;border:1px solid var(--borde);border-radius:12px;margin-bottom:20px}label{display:block;margin:12px 0 5px}input{width:100%;max-width:500px;font:inherit;padding:10px;border:1px solid var(--borde);border-radius:8px;color:var(--texto);background:var(--superficie)}button{font:inherit;padding:10px 16px;margin-top:16px;cursor:pointer}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:12px;border-bottom:1px solid var(--borde)}.error{color:var(--rojo)}',
    contenido: '<div class="wrap"><p id="cuentas-aviso" role="status"></p><section class="card"><h2>Cuentas registradas</h2><div id="cuentas-lista"></div></section><section class="card"><h2>Crear cuenta independiente</h2><p>Cada cuenta conserva sus clientes, WhatsApp, claves de API y usuarios.</p><form id="cuentas-form"><label>Nombre de la cuenta</label><input id="cuenta-negocio" required maxlength="80"><label>Nombre del administrador</label><input id="cuenta-nombre" required maxlength="80"><label>Usuario</label><input id="cuenta-usuario" required maxlength="60" autocomplete="off"><label>Contraseña</label><input id="cuenta-clave" required type="password" autocomplete="new-password"><br><button type="submit">Crear cuenta</button></form></section></div>',
    script: String.raw`(function(){var $=function(id){return document.getElementById(id);};function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}async function api(method,body){var r=await fetch('/admin/cuentas-plataforma',{method:method||'GET',credentials:'same-origin',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});if(r.status===401){location.href='/login';throw Error('Inicia sesión.');}var d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo completar la operación.');return d;}function aviso(t,error){$('cuentas-aviso').textContent=t;$('cuentas-aviso').className=error?'error':'';}async function cargar(){var d=await api();$('cuentas-lista').innerHTML='<table><thead><tr><th>Cuenta</th><th>Identificador</th><th>Estado</th><th>Registro</th></tr></thead><tbody>'+d.cuentas.map(function(c){return '<tr><td>'+esc(c.nombre)+'</td><td>'+esc(c.slug)+'</td><td>'+esc(c.estado)+'</td><td>'+esc(new Date(c.creadaAt).toLocaleString('es-PE'))+'</td></tr>';}).join('')+'</tbody></table>';} $('cuentas-form').onsubmit=async function(e){e.preventDefault();var b=this.querySelector('button');b.disabled=true;try{await api('POST',{tienda:$('cuenta-negocio').value,nombre:$('cuenta-nombre').value,usuario:$('cuenta-usuario').value,clave:$('cuenta-clave').value});$('cuenta-clave').value='';aviso('Cuenta creada. Su administrador puede entrar desde /login.');await cargar();}catch(err){aviso(err.message,true);}finally{b.disabled=false;}};cargar().catch(function(e){aviso(e.message,true);$('cuentas-form').hidden=true;});})();`,
  });
}
