import { appShell } from './shell.js';

export interface PanelOpts { configured: boolean; nombreNegocio: string; demo?: boolean }

const CSS = `
.wrap{max-width:1400px;margin:auto}.card{background:var(--superficie);border:1px solid var(--borde);border-radius:12px;padding:22px;margin-bottom:18px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin:14px 0}.muted{color:var(--texto-suave)}
label{display:block;margin:14px 0 5px}input,textarea,select{font:inherit;color:var(--texto);background:var(--superficie);border:1px solid var(--borde);border-radius:8px;padding:10px;width:100%}input[type=checkbox]{width:auto}textarea{min-height:100px}
button,.btn{font:inherit;padding:10px 16px;border-radius:8px;border:1px solid var(--borde);background:var(--primario);color:var(--primario-texto);cursor:pointer;text-decoration:none}button:disabled{opacity:.5;cursor:wait}
table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:10px;border-bottom:1px solid var(--borde);vertical-align:top}.tablewrap{overflow:auto}.error{color:var(--rojo);white-space:pre-wrap}.notice{white-space:pre-wrap}.number{font-size:30px;font-weight:700}.hidden{display:none!important}code{overflow-wrap:anywhere}pre{white-space:pre-wrap}
`;

export function panelPage(opts: PanelOpts): string {
  return appShell({ titulo: 'Inicio', subtitulo: 'API, WhatsApp y atención de pedidos', nombreNegocio: opts.nombreNegocio, css: CSS,
    contenido: `<div class="wrap">
<p id="panel-aviso" class="notice" role="status"></p>
<section id="tab-inicio" class="card"><h2>Estado del sistema</h2><div id="inicio-cifras" class="grid"></div><div class="actions"><a class="btn" href="/hoy">Pedidos GSG</a><a class="btn" href="/chat">Chats</a><a class="btn" href="/conexion-gsg">API y endpoint</a><a class="btn" href="/salud">Salud</a></div><div id="inicio-avisos"></div></section>
<section id="tab-ia" class="card hidden"><h2>Asistente IA</h2><p class="muted">Configura el modelo y carga la ficha de productos: nombres, precios, stock y condiciones que debe conocer.</p>
<form id="ia-form"><div class="grid"><div><label><input id="ia-activa" type="checkbox"> Activar IA</label><label>Proveedor</label><select id="ia-proveedor"><option value="puter">Puter</option><option value="openai">API compatible con OpenAI</option></select><div id="ia-servicio-grupo"><label>Servicio de la API</label><select id="ia-servicio"><option value="openai">OpenAI</option><option value="groq">Groq</option><option value="openrouter">OpenRouter</option><option value="together">Together AI</option><option value="deepseek">DeepSeek</option><option value="google">Google AI Studio</option><option value="mistral">Mistral</option></select></div><label for="ia-modelo">Modelo</label><div class="actions"><select id="ia-modelo"><option value="">Pega la clave y pulsa «Actualizar lista»</option></select><button id="ia-modelos-cargar" type="button">Actualizar lista</button></div><p id="ia-modelos-estado" class="muted">Elige el servicio y detecta los modelos disponibles con tu API.</p><label>Clave API</label><input id="ia-token" type="password" autocomplete="new-password" placeholder="Vacío conserva la clave actual"><p id="ia-credencial" class="muted"></p></div><div><label>Nombre del asistente</label><input id="ia-nombre" maxlength="60"><label>Ficha de productos y conocimiento</label><textarea id="ia-conocimiento" maxlength="20000" rows="10"></textarea><label>Instrucciones de respuesta</label><textarea id="ia-instrucciones" maxlength="4000"></textarea><label>Cuando el cliente pide estas palabras, pasar a una persona</label><input id="ia-derivar" maxlength="500"><label><input id="ia-avisar" type="checkbox"> Avisar al supervisor al derivar</label></div></div><div class="actions" data-admin><button type="submit">Guardar IA</button><button id="ia-comprobar" type="button">Comprobar conexión</button><a href="/entrenamiento">Entrenamiento</a></div><p id="ia-comprobar-estado" class="muted" role="status" aria-live="polite"></p></form>
<details><summary>Voz y transcripción de WhatsApp</summary><form id="voz-form"><label><input id="voz-activa" type="checkbox"> Activar voz</label><label>Clave de ElevenLabs</label><input id="voz-clave" type="password" autocomplete="new-password" placeholder="Vacío conserva la clave"><label>ID de voz</label><input id="voz-id"><button type="submit" data-admin>Guardar voz</button></form><p id="voz-estado" class="muted"></p></details>
</section>
<section id="tab-plantillas" class="card hidden"><h2>Plantillas de WhatsApp</h2><div class="actions" data-admin><button id="tpl-sync">Sincronizar con Meta</button><button id="tpl-push">Subir plantillas a Meta</button></div><div id="tpl-lista" class="tablewrap"></div><details data-admin><summary>Crear o editar una plantilla propia</summary><form id="tpl-form"><div class="grid"><div><label>Nombre</label><input id="tpl-name" required pattern="[a-z0-9_]+" minlength="3" maxlength="120"><label>Idioma</label><input id="tpl-language" value="es" required maxlength="10"></div><div><label>Categoría</label><select id="tpl-category"><option>UTILITY</option><option>AUTHENTICATION</option><option>MARKETING</option></select><label>Descripción de cada variable, una por línea</label><textarea id="tpl-variables"></textarea></div></div><label>Mensaje</label><textarea id="tpl-body" required minlength="10" maxlength="1024"></textarea><label>Pie de mensaje</label><input id="tpl-footer" maxlength="60"><button type="submit">Guardar plantilla</button></form></details></section>
<section id="tab-historial" class="card hidden"><h2>Historial y errores</h2><p>Los pedidos con mensajes fallidos se corrigen y reintentan desde <a href="/hoy">Pedidos GSG</a>.</p><div class="actions"><select id="historial-estado" aria-label="Estado"><option value="">Todos</option><option value="failed">Fallidos</option><option value="sent">Enviados</option><option value="delivered">Entregados</option><option value="read">Leídos</option><option value="blocked_by_gate">Bloqueados</option></select><button id="historial-refrescar">Actualizar</button><a id="historial-exportar" href="/admin/deliveries.csv">Exportar</a></div><h3>Mensajes de WhatsApp</h3><div id="historial-lista" class="tablewrap"></div><h3>Recepciones de Postman / GSG</h3><p class="muted">Cada llamada a POST /api/v1/entregas, con su resultado HTTP, referencias y errores de validación. No se guardan teléfonos ni claves.</p><div id="recepciones-api-lista" class="tablewrap"></div></section>
<section id="tab-usuarios" class="card hidden" data-admin><h2>Usuarios del equipo</h2><div id="usuarios-lista" class="tablewrap"></div><form id="usuario-form"><h3>Crear usuario</h3><div class="grid"><div><label>Nombre</label><input id="u-nombre" required maxlength="80"><label>Usuario</label><input id="u-usuario" required maxlength="60" autocomplete="off"></div><div><label>Contraseña</label><input id="u-clave" type="password" required autocomplete="new-password"><label>Rol</label><select id="u-rol"><option value="operador">Operador</option><option value="admin">Administrador</option><option value="superadmin" data-super>Superadministrador</option></select></div></div><button type="submit">Crear usuario</button></form></section>
<section id="tab-configuracion" class="card hidden" data-admin><h2>Ajustes</h2><form id="ajustes-form"><label>Nombre del negocio</label><input id="aj-nombre" maxlength="100"><label>Teléfono del supervisor</label><input id="aj-supervisor" inputmode="tel"><div class="grid"><div><label>Inicio del horario (0–23)</label><input id="aj-inicio" type="number" min="0" max="23"></div><div><label>Fin del horario (0–23)</label><input id="aj-fin" type="number" min="0" max="23"></div></div><div class="actions"><button type="submit">Guardar ajustes</button><a href="/automatizacion-gsg">Automatización GSG</a><a href="/salud">Salud y ritmo</a></div></form><p>Las claves de recepción se administran en <a href="/conexion-gsg">API y endpoint GSG</a>.</p></section>
<section id="tab-actividad" class="card hidden" data-admin><h2>Actividad del equipo</h2><div id="actividad-lista" class="tablewrap"></div></section>
<section id="tab-mi-cuenta" class="card hidden"><h2>Mi cuenta</h2><p id="mi-identidad"></p><form id="clave-form"><label>Contraseña actual</label><input id="clave-actual" type="password" required autocomplete="current-password"><label>Nueva contraseña</label><input id="clave-nueva" type="password" required autocomplete="new-password"><button type="submit">Cambiar contraseña</button></form></section>
<section id="tab-pedidos" class="card hidden"><h2>Pedidos del chat</h2><div id="pedidos-chat" class="tablewrap"></div></section>
</div>`,
    script: String.raw`
(function(){
var $=function(id){return document.getElementById(id);}, yo=null;
var esc=function(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
async function api(url,method,body){var r=await fetch(url,{method:method||'GET',credentials:'same-origin',cache:'no-store',headers:body===undefined?{}:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(r.status===401){location.href='/login?next='+encodeURIComponent(location.pathname+location.hash);throw Error('Inicia sesión.');}var d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo completar la operación ('+r.status+').');return d;}
function aviso(texto,error){$('panel-aviso').textContent=texto;$('panel-aviso').className=error?'error':'notice';}
function tabla(id,cab,rows){$(id).innerHTML=rows.length?'<table><thead><tr>'+cab.map(function(c){return '<th>'+esc(c)+'</th>';}).join('')+'</tr></thead><tbody>'+rows.map(function(row){return '<tr>'+row.map(function(c){return '<td>'+esc(c)+'</td>';}).join('')+'</tr>';}).join('')+'</tbody></table>':'<p class="muted">No hay registros.</p>';}
function fecha(d){return d?new Date(d).toLocaleString('es-PE'):'—';}
function evento(id,fn,event){$(id).addEventListener(event||'click',async function(e){e.preventDefault();var b=e.currentTarget.tagName==='FORM'?e.currentTarget.querySelector('button[type=submit]'):e.currentTarget;if(b)b.disabled=true;try{await fn();}catch(err){aviso(err.message,true);}finally{if(b)b.disabled=false;}});}
async function inicio(){var r=await Promise.all([api('/health'),api('/admin/health'),api('/admin/resumen'),api('/admin/avisos')]);var h=r[1],res=r[2];var cifras=[['API',r[0].ok?'Disponible':'No disponible'],['WhatsApp',r[0].connected?'Conectado':'Sin conexión'],['Pedidos GSG',res.entregas?res.entregas.total:0],['Mensajes enviados hoy',h.sentToday],['Cupo diario',h.dailyCap]];$('inicio-cifras').innerHTML=cifras.map(function(c){return '<div class="card"><p>'+esc(c[0])+'</p><div class="number">'+esc(c[1])+'</div></div>';}).join('');var avisos=r[3].avisos||[];$('inicio-avisos').innerHTML=avisos.map(function(a){return '<p>'+esc(a.texto)+'</p>';}).join('')||'<p class="muted">Sin alertas pendientes.</p>';}
async function ia(){var d=await api('/admin/ia');$('ia-activa').checked=d.activa;$('ia-proveedor').value=d.proveedor;$('ia-servicio').value=d.servicio==='otro'?'openai':d.servicio;modeloGuardado=d.modelo||'';$('ia-nombre').value=d.nombreAsistente;$('ia-conocimiento').value=d.conocimiento;$('ia-instrucciones').value=d.instrucciones;$('ia-derivar').value=d.derivarSi;$('ia-avisar').checked=d.avisarDerivacion;$('ia-credencial').textContent=d.tieneToken?'Clave guardada.':'Falta configurar la clave.';$('ia-servicio-grupo').hidden=d.proveedor!=='openai';if(d.proveedor==='puter')ponerModelos(d.modelosGratis||[],'Modelos gratuitos disponibles en Puter.');else cargarModelosIa().catch(function(e){$('ia-modelos-estado').textContent=e.message;});try{var v=await api('/admin/voz');$('voz-activa').checked=v.activa;$('voz-id').value=v.vozId||'';$('voz-estado').textContent=v.tieneClave?'Clave de voz guardada.':'Voz sin clave.';}catch(e){$('voz-estado').textContent=e.message;}}
var modeloGuardado='';
/* El modelo se elige de una lista: los de la API (o los gratis de Puter), y el guardado aunque ya no venga. */
function ponerModelos(lista,detalle,elegido){var sel=$('ia-modelo');var actual=elegido||sel.value||modeloGuardado;var ids=(lista||[]).map(function(m){return typeof m==='string'?m:m.id;}).filter(Boolean);if(actual&&ids.indexOf(actual)<0)ids.unshift(actual);sel.innerHTML=ids.length?'':'<option value="">No hay modelos: revisa la clave y pulsa «Actualizar lista»</option>';ids.forEach(function(id){var op=document.createElement('option');op.value=id;op.textContent=id+(id===modeloGuardado?' (guardado)':'');sel.appendChild(op);});if(actual)sel.value=actual;if(detalle)$('ia-modelos-estado').textContent=detalle;}
async function cargarModelosIa(){if($('ia-proveedor').value==='puter')return;var boton=$('ia-modelos-cargar');boton.disabled=true;$('ia-modelos-estado').textContent='Consultando los modelos disponibles…';try{var r=await api('/admin/ia/modelos','POST',{servicio:$('ia-servicio').value,clave:$('ia-token').value});ponerModelos(r.modelos||[],r.detalle||'',$('ia-modelo').value||modeloGuardado||r.elegido||'');}finally{boton.disabled=false;}}
evento('ia-modelos-cargar',cargarModelosIa);$('ia-token').onchange=function(){if($('ia-token').value.trim())cargarModelosIa().catch(function(e){$('ia-modelos-estado').textContent=e.message;});};$('ia-servicio').onchange=function(){cargarModelosIa().catch(function(e){$('ia-modelos-estado').textContent=e.message;});};$('ia-proveedor').onchange=function(){var puter=$('ia-proveedor').value==='puter';$('ia-servicio-grupo').hidden=puter;if(puter)api('/admin/ia').then(function(d){ponerModelos(d.modelosGratis||[],'Modelos gratuitos disponibles en Puter.');}).catch(function(){});else cargarModelosIa().catch(function(e){$('ia-modelos-estado').textContent=e.message;});};
evento('ia-form',async function(){var body={activa:$('ia-activa').checked,proveedor:$('ia-proveedor').value,servicio:$('ia-servicio').value,modelo:$('ia-modelo').value,baseUrl:'',nombreAsistente:$('ia-nombre').value,conocimiento:$('ia-conocimiento').value,instrucciones:$('ia-instrucciones').value,derivarSi:$('ia-derivar').value,avisarDerivacion:$('ia-avisar').checked};if($('ia-token').value)body.token=$('ia-token').value;await api('/admin/ia','POST',body);$('ia-token').value='';aviso('IA guardada.');await ia();},'submit');
evento('ia-comprobar',async function(){var caja=$('ia-comprobar-estado');caja.className='muted';caja.textContent='Comprobando la conexión con la IA…';try{var d=await api('/admin/ia/probar-conexion','POST',{proveedor:$('ia-proveedor').value,servicio:$('ia-servicio').value,modelo:$('ia-modelo').value,token:$('ia-token').value||undefined});var p=d.prueba||{};caja.className=d.ok?'notice':'error';caja.textContent=d.ok?'✓ La IA responde correctamente'+(p.modelo?' con '+p.modelo:'')+(p.ms?' ('+p.ms+' ms)':'')+'.':'✗ No responde: '+(p.detalle||'error desconocido');}catch(err){caja.className='error';caja.textContent='✗ No se pudo comprobar: '+err.message;}});
evento('voz-form',async function(){var b={activa:$('voz-activa').checked,vozId:$('voz-id').value};if($('voz-clave').value)b.clave=$('voz-clave').value;await api('/admin/voz','POST',b);$('voz-clave').value='';aviso('Voz guardada.');},'submit');
async function plantillas(){var d=await api('/admin/templates');tabla('tpl-lista',['Nombre','Idioma','Estado','Mensaje'],d.map(function(t){return [t.name,t.language,t.status,t.body];}));}
evento('tpl-sync',async function(){await api('/admin/templates/sync','POST',{});await plantillas();aviso('Plantillas sincronizadas.');});
evento('tpl-push',async function(){var d=await api('/admin/templates/push','POST',{});aviso('Solicitud de subida procesada.');await plantillas();});
evento('tpl-form',async function(){await api('/admin/templates','POST',{name:$('tpl-name').value,language:$('tpl-language').value,category:$('tpl-category').value,body:$('tpl-body').value,variables:$('tpl-variables').value.split('\n').map(function(x){return x.trim();}).filter(Boolean),footer:$('tpl-footer').value});aviso('Plantilla guardada.');await plantillas();},'submit');
async function historial(){var filtro=$('historial-estado').value;var q=filtro?'?status='+encodeURIComponent(filtro):'';var r=await Promise.all([api('/admin/deliveries'+q),api('/admin/gsg/recepciones')]);var d=r[0],entradas=r[1].items||[];$('historial-exportar').href='/admin/deliveries.csv'+q;tabla('historial-lista',['Fecha','Cliente','Teléfono','Estado','Error'],d.map(function(x){return [fecha(x.sentAt||x.queuedAt),x.name,x.phone,x.status,[x.errorCode,x.errorTitle].filter(Boolean).join(' · ')];}));tabla('recepciones-api-lista',['Fecha','HTTP','Resultado','Pedidos','Creados','Repetidos','Descartados','Referencias','Error'],entradas.map(function(x){var v=x.detalle||{};var estado=({'recibido':'Recibido','repetido':'Ya existían','error':'Error'})[v.estado]||v.estado||'';var refs=(v.referencias||[]).join(', ')+(v.referenciasRestantes?' … +'+v.referenciasRestantes:'');var detalle=(v.error||'')+(v.detalles&&v.detalles.length?' · '+v.detalles.map(function(e){return [e.campo,e.mensaje].filter(Boolean).join(': ');}).join(' | '):'');return [fecha(x.at),v.http||'',estado,v.recibidas||0,v.creadas||0,v.repetidas||0,v.descartadas||0,refs,detalle];}));}
evento('historial-refrescar',historial);$('historial-estado').onchange=function(){historial().catch(function(e){aviso(e.message,true);});};
async function usuarios(){var d=await api('/admin/usuarios');tabla('usuarios-lista',['Nombre','Usuario','Rol','Estado'],d.map(function(u){return [u.nombre,u.usuario,u.rol,u.activo?'Activo':'Desactivado'];}));var box=document.createElement('div');box.className='actions';d.forEach(function(u){var b=document.createElement('button');b.type='button';b.textContent=(u.activo?'Desactivar ':'Activar ')+u.usuario;b.disabled=u.id===yo.id; b.onclick=async function(){try{await api('/admin/usuarios/'+encodeURIComponent(u.id),'POST',{activo:!u.activo});await usuarios();}catch(e){aviso(e.message,true);}};box.appendChild(b);});$('usuarios-lista').appendChild(box);}
evento('usuario-form',async function(){await api('/admin/usuarios','POST',{nombre:$('u-nombre').value,usuario:$('u-usuario').value,clave:$('u-clave').value,rol:$('u-rol').value});$('u-clave').value='';aviso('Usuario creado.');await usuarios();},'submit');
async function ajustes(){var a=await api('/admin/ajustes');$('aj-nombre').value=a.efectivo.nombreNegocio;$('aj-supervisor').value=a.efectivo.supervisor||'';$('aj-inicio').value=a.efectivo.horario.inicio;$('aj-fin').value=a.efectivo.horario.fin;}
evento('ajustes-form',async function(){await api('/admin/ajustes','POST',{nombreNegocio:$('aj-nombre').value,avisos:{supervisor:$('aj-supervisor').value||null},horario:{inicio:Number($('aj-inicio').value),fin:Number($('aj-fin').value)}});aviso('Ajustes guardados.');},'submit');
async function actividad(){var d=await api('/admin/actividad');tabla('actividad-lista',['Fecha','Usuario','Acción','Detalle'],(d.items||d.registros||[]).map(function(x){return [fecha(x.at||x.en),x.usuario||x.usuarioNombre,d.etiquetas&&d.etiquetas[x.accion]||x.accion,JSON.stringify(x.detalle)];}));}
evento('clave-form',async function(){await api('/admin/mi-clave','POST',{actual:$('clave-actual').value,nueva:$('clave-nueva').value});$('clave-actual').value='';$('clave-nueva').value='';aviso('Contraseña actualizada.');},'submit');
async function pedidos(){var d=await api('/api/v1/pedidos');tabla('pedidos-chat',['Cliente','Estado','Total'],(Array.isArray(d)?d:d.pedidos||[]).map(function(x){return [x.nombre||x.phone,x.estado,x.total];}));}
var cargas={inicio:inicio,ia:ia,plantillas:plantillas,historial:historial,usuarios:usuarios,configuracion:ajustes,actividad:actividad,pedidos:pedidos,'mi-cuenta':async function(){$('mi-identidad').textContent=yo.nombre+' · '+yo.usuario;}};
async function mostrar(){var t=location.hash.slice(1)||'inicio';if(t==='estado'||t==='salud'){location.replace('/salud');return;}if(t==='ubicaciones'){location.replace('/mapa');return;}if(t==='integraciones'){location.replace('/conexion-gsg');return;}if(!cargas[t]){history.replaceState(null,'','#inicio');t='inicio';}document.querySelectorAll('[id^=tab-]').forEach(function(s){s.classList.toggle('hidden',s.id!=='tab-'+t);});if(['usuarios','configuracion','actividad'].includes(t)&&yo.rol!=='admin'){aviso('Esta pantalla requiere un administrador.',true);return;}aviso('');try{await cargas[t]();}catch(e){aviso(e.message,true);}}
async function iniciar(){try{yo=await api('/admin/yo');document.querySelectorAll('[data-admin]').forEach(function(e){if(yo.rol!=='admin')e.hidden=true;});document.querySelectorAll('[data-super]').forEach(function(e){if(!yo.super)e.remove();});window.addEventListener('hashchange',mostrar);await mostrar();}catch(e){aviso(e.message,true);}}
iniciar();
})();`,
  });
}
